server:
  port: 8080
log:
  level: error
  format: text
cluster:
  nodes:
    - address: "http://localhost:8081"
    - address: "http://localhost:8082"
    - address: "http://localhost:8083"
  policy: "rr"