server:
  port: 8080
log:
  level: error
  format: text
cluster:
  nodes:
    - address: "http://localhost:8080"
    - address: "http://localhost:8080"
    - address: "http://localhost:8080"
  policy: "rr"